apiVersion: v1
kind: PersistentVolume
metadata:
  name: todos-db
  namespace: 101-todo
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/todos-db/
  persistentVolumeReclaimPolicy: Retain
