apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: 101-todo
  labels:
    app: 101-todo
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: 101-todo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
